#Evolution Population / Nourriture / Energie par Continent

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

library(flexdashboard)

library(tidyverse)

setwd("C:/Users/Cefim/Desktop/cours data/cours_R/seq_bookdown/template_bookdown/template")

# aide
# flexdashboard https://shiny.rstudio.com/articles/dashboards.html


```


## Column 1 {data-width=650}

### Evolution de la population


```{r}


population<-read_delim("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.csv",                                
                        skip=16,
                        na="...",
                        locale=locale(decimal_mark=","))|> 
                        rename(region=3)  |> 
                        select(region,Type,"1950":"2020") |> 
                        pivot_longer(cols="1950":"2020",
                                     names_to = "annee",
                                     values_to="population")


population_continent <- population |> 
  filter(Type == "Region")

ggplot(population_continent)+
  aes(annee, population, colour=region, group=1)+
  geom_point()+
  geom_line()+
  labs(x="Année",
       y="Population")



```




## Column 2 {dat-width=350, .tabset}

### Production de Nourriture

```{r}

food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding="ISO-8859-1")) |>
                  select(-ends_with("F")) |> 
                  pivot_longer(cols=Y1961:Y2020,
                               names_to="annee",
                               values_to = "valeur") |> 
                  mutate(annee=str_remove(annee,"Y"))


food_continent <- food |>
  filter( Area=="Africa"|
          Area=="Northern America"|
          Area=="Central America"|
          Area=="South America"|
          Area=="Asia"|
          Area=="Europe"|
          Area=="Oceania",
          Element=="Production") |> 
  filter(str_detect(Item,pattern="Total"))



ggplot(food_continent)+
  aes(x=annee,y=valeur,colour=Item)+
  geom_point()+
  geom_line()+
  facet_grid(~Area)


```


### Consommation d'Energie

```{r}


energy<-read_delim("owid-energy-data__OWID.csv") |> 
  select(1:3,ends_with("consumption"))|> 
  pivot_longer(cols=4:16,
               names_to="type_energie",
               values_to="consommation")


type_energy_continent <- energy |> 
     filter(country=="Africa"|
            country=="South & Central America"|
            country=="North America"|
            country=="Asia Pacific"|
            country=="Europe"|
            country=="Australia") |> 
    filter(type_energie=="biofuel_consumption"|
           type_energie=="coal_consumption"|
           type_energie=="gas_consumption"|
           type_energie=="hydro_consumption"|
           type_energie=="nuclear_consumption"|
           type_energie=="oil_consumption"|
           type_energie=="solar_consumption"|
           type_energie=="wind_consumption")
    

ggplot(type_energy_continent)+
  aes(x=year, y=consommation, colour=type_energie)+
  geom_point()+
  geom_line()+
  facet_grid(~country)


```













