# Evolution Monde

```{r include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

library(flexdashboard)

library(tidyverse)

library(countrycode)

#setwd("C:/Users/Cefim/Desktop/cours data/cours_R/seq_bookdown/template_bookdown/template")


```


Column {data-with=650}
------

### Répartition de la population

```{r}

world <- map_data("world") |> 
  mutate(iso_code2=countrycode(region, origin = "country.name", destination = "iso3c")) |>
  mutate(iso_pays=countrycode(iso_code2, origin = "iso3c", destination = "country.name"))


population<-read_delim("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.csv",                                
                        skip=16,
                        na="...",
                        locale=locale(decimal_mark=","))|> 
                        rename(region=3)  |> 
                        select(region,Type,"1950":"2020") |> 
                        pivot_longer(cols="1950":"2020",
                                     names_to = "annee",
                                     values_to="population") |> 
                        filter(annee==2020, Type=="Country/Area") |> 
                        mutate(iso_code2=countrycode(region, origin = "country.name", destination = "iso3c")) |>
                        mutate(iso_pays=countrycode(iso_code2, origin = "iso3c", destination = "country.name"))




pop_world <- left_join(world, population, by=c("iso_pays"="iso_pays"))

ggplot(pop_world)+
  aes(long, lat)+
  geom_polygon(aes( fill = population, group = group), colour = "black")+
  scale_fill_viridis_c()



```


Column {data-with=350}
------

### Répartition de la production de nourriture


```{r}


food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding="ISO-8859-1")) |>
                  select(-ends_with("F")) |> 
                  pivot_longer(cols=Y1961:Y2020,
                               names_to="annee",
                               values_to = "valeur") |> 
                  mutate(annee=str_remove(annee,"Y"))|> 
                  filter(Element=="Production") |> 
                  filter(str_detect(Item,pattern="Total"))  |> 
                  mutate(iso_code2=countrycode(Area, origin = "country.name", destination = "iso3c")) |>
                  mutate(iso_pays=countrycode(iso_code2, origin = "iso3c", destination = "country.name")) |> 
                  filter(annee=='2020',Item=="Cereals, Total")
                

food_world <- left_join(world, food, by=c("iso_pays"="iso_pays"))

ggplot(food_world)+
  aes(long, lat)+
  geom_polygon(aes( fill = valeur , group = group), colour = "black")+
  scale_fill_viridis_c()




```



###  Répartition de la consommation d'énergie



```{r}

energy<-read_delim("owid-energy-data__OWID.csv") |> 
  select(1:3,ends_with("consumption"))|> 
  pivot_longer(cols=4:16,
               names_to="type_energie",
               values_to="consommation") |>
  filter(type_energie=="coal_consumption", year=="2000") |> 
  mutate(iso_code2=countrycode(country, origin = "country.name", destination = "iso3c")) |>
  mutate(iso_pays=countrycode(iso_code2, origin = "iso3c", destination = "country.name")) |> 
  filter(consommation > 0)
  
energy_world <- left_join(world, energy, by=c("iso_pays"="iso_pays"))


ggplot(energy_world)+
  aes(long, lat)+
  geom_polygon(aes( fill = consommation , group = group), colour = "black")+
  scale_fill_viridis_c()

```


